### PR TITLE
Author amendment document changes extension

### PR DESCRIPTION
**Pull request by duncandewhurst**

### CODE REVIEW

**Review by odscjen — COMMENTED** [review]
The `document` object contains the field `dateModified` that is similar to the new field `documentsChangeDate` in this extension. Should the README contain some general guidance on when to use this extension instead of or in addition to `documents.dateModified`? I can see this being confusing if anyone tries to use this extension for non-eforms data.

Otherwise this all looks fine.

**Comment by duncandewhurst** [comment]
Ah, good spot. Given that the semantics of the two fields are the same I wonder if we should instead map BT-719 to `tender.documents.dateModified`. The procurement documents fields in eForms are mandatory so there should also be a document to set `.dateModified` on.

The only downsides that I can see are:

* Only the latest modification date would be reflected in a compiled release. Whereas, all the dates would be available if mapped to `tender.amendments.documentsChangeDate`.
* The mapping would be more complicated because, for changes associated with a lot, it would involve looking up the document in `tender.documents` with 'biddingDocuments' in `.role` and the lot identified in `<efbc:ChangedSectionIdentifier>` in `.relatedLots`.

@jpmckinney what do you think?

**Comment by jpmckinney** [comment]
It makes sense to map to `documents`. I think it's similar complexity, because looking up the award (per BT-140) is a bit complicated already.

I think it's fine to preserve only the most recent date (in the case of a document being amended multiple times).

If we change the mapping for BT-719 in this way, what about BT-718? Right now it adds a `documentsChanged` boolean, but as a user, I'm probably comparing e.g. my last access date to the modifiedDate, so maybe it can be discarded?

**Comment by jpmckinney** [comment]
By the way, GMail is merging multiple "Author extension" PRs into one thread, which is confusing, so for any additional extensions you can add the title of the extension in the PR name to avoid that.

**Comment by duncandewhurst** [comment]
> By the way, GMail is merging multiple "Author extension" PRs into one thread, which is confusing, so for any additional extensions you can add the title of the extension in the PR name to avoid that.

Will do. I'll rename the existing PRs as I come to them, too.

**Comment by duncandewhurst** [comment]
> If we change the mapping for BT-719 in this way, what about BT-718? Right now it adds a `documentsChanged` boolean, but as a user, I'm probably comparing e.g. my last access date to the modifiedDate, so maybe it can be discarded?

From the perspective of a bidder, I think checking `dateModified` is probably sufficient, so it depends on whether there are any use cases that depend on knowing whether a specific amendment included a change to documents, or counting the number of amendments that include a change for documents. I don't know if there are use cases relating to integrity or efficiency to do with identifying processes in which the documents changed many times. That said, that could still be done by looking at `dateModified` in a versioned release. Unless you know of any, I'm happy to discard it.

**Comment by jpmckinney** [comment]
Let's discard it. I think it's probably a bit too narrow for there to be integrity red flags developed around it.

**Comment by duncandewhurst** [comment]
I've updated `guidance.yaml` (9c2cba50a68ef7e02583109ec0ffb7d3b7eef1ad).

This extension is no longer needed so, in order to preserve this discussion, I'll archive it rather than delete it.

**Pull request closed without merging**
